ldda_prediction=0, add .gitignore
biocad/EnQA pull request #1
Opened 2022-11-21 14:04 UTC by egor4k

2022-11-21 14:20 UTC, NataZen approved these changes

2022-12-13 22:23 UTC, wlad111 requested changes
Самое основное -- разобраться со смысловой частью определения интерфейса, если непонятно как, то лучше сразу пиши, я поясню еще раз

2022-12-13 22:23 UTC, wlad111 commented on train.py
> +            path_to_complex=Path(path_docked+'/'+sample)
Предлагаю `path_docked` сразу обернуть в `Path` и уже здесь воспользоваться оператором `/`, который определен для класса `Path`. Например, это бы выглядело как: `path_to_complex = path_docked / sample`

2022-12-13 22:23 UTC, wlad111 commented on train.py
> +            contacts=get_interface(Path(path_docked+'/'+sample+'/real.pdb'))
Аналогично

2022-12-13 22:23 UTC, wlad111 commented on train.py
> +            mapping=get_raw_mapping(path_to_complex,'','real_joined.pdb','','real.pdb')
Стоп, кажется, тут немного странные вещи происходят. Нам же нужно получить маппинг остатков из `_joined` структуры в `_temp` (ну или наоборот, как посмотреть). А тут последним аргументом стоит `real`, которая, к сожалению, нам далеко не всегда подойдет, потому что в ней, вообще говоря, больше чем 2 цепи, и интерфейс у нее не совсем корректно находить. Именно для этого и был нужен код, в котором я сохранял `_temp` структуру, где все сведено до 2 цепей (1 цепь антитело  и 1 цепь антиген)

2022-12-15 23:23 UTC, wlad111 requested changes
В остальном вроде норм

2022-12-15 23:23 UTC, wlad111 commented on train.py
> +# python3 train.py --train /mnt/volume/outputs_vacation/processed --validation /mnt/volume/outputs_vacation/processed --output outputs/ --epochs 2 --set-train train.txt --set-validation valid.txt
new line

2022-12-23 13:25 UTC, NataZen approved these changes

2022-12-23 13:25 UTC, NataZen commented on metrics.py
> +def calculate_dockq():
Стоит это удалить, потому что пока непонятно, будем ли мы вообще считать dockq.

2022-12-23 13:25 UTC, NataZen commented on metrics.py
> +import torch
Зачем torch здесь?

2022-12-23 13:25 UTC, NataZen commented on metrics.py
> +def get_chains_to_merge(path_to_structure, ab_chain_names):
Если уже где-то есть типизация, то давайте ее и здесь добавим

2022-12-23 13:25 UTC, NataZen commented on metrics.py
> +def parse_chains(comp_name):
Аналогично

2022-12-23 13:25 UTC, NataZen commented on metrics.py
> +def calculate_fnat(path_to_docked_structure, path_to_reference_structure, ab_chains):
Давай удалим все, что не относится к подсчету lddt по интерфейсу. Все остальное и так есть в CRank.

2022-12-23 13:25 UTC, NataZen commented on train.py
> +            merge_chains(ab_chains,ag_chains,'ref_temp.pdb')
Стоит это все убрать в препроцессинг. Можно это сделать в следующем PR.

2022-12-26 11:33 UTC, egor4k commented on metrics.py
> +    return lddt_list[tensor(lddts)]
здесь нужен tensor from torch

2022-12-26 12:16 UTC, NataZen approved these changes

2022-12-26 12:36 UTC, merged